engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
    checks:
      Similar code:
        enabled: false
  fixme:
    enabled: true
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
ratings:
  paths:
  - "**.py"
  - "**.pyx"
  - "**.pxd"
exclude_paths:
- tests/
- doc/