sudo: required
language: python
matrix:
    include:
        - python: "2.6"
          env: NUMPY_VERSION=1.9.2 SCIPY_VERSION=0.15.1 MATPLOTLIB_VERSION=1.4.3
        - python: "2.7"
          env: NUMPY_VERSION=1.10.2 SCIPY_VERSION=0.16.1 MATPLOTLIB_VERSION=1.5.1
        - python: "3.3"
          env: NUMPY_VERSION=1.9.2 SCIPY_VERSION=0.15.1 MATPLOTLIB_VERSION=1.4.3
        - python: "3.4"
          env: NUMPY_VERSION=1.10.2 SCIPY_VERSION=0.16.1 MATPLOTLIB_VERSION=1.5.1
        - python: "3.5"
          env: NUMPY_VERSION=1.10.2 SCIPY_VERSION=0.16.1 MATPLOTLIB_VERSION=1.5.1
cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
install:
  - conda create --yes -q -n test_environment python=$TRAVIS_PYTHON_VERSION nomkl pip setuptools cython numpy=$NUMPY_VERSION scipy=$SCIPY_VERSION nose matplotlib=$MATPLOTLIB_VERSION six mock h5py
  - source activate test_environment
  - pip install pep8 python-coveralls codecov
  - pip install -e . -q --no-deps
script:
  - nosetests --with-coverage --cover-package=neutronpy --logging-level=INFO
after_success:
  - codecov
  - coveralls
