sudo: required
language: generic
matrix:
  include:
    - os: linux
      env: PYTHON_VERSION=2.6 NUMPY_VERSION=1.9.2 SCIPY_VERSION=0.15.1 MATPLOTLIB_VERSION=1.4.3 LMFIT_VERSION=0.9.1
    - os: linux
      env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.10.2 SCIPY_VERSION=0.16.1 MATPLOTLIB_VERSION=1.5.1 LMFIT_VERSION=0.9.3
    - os: linux
      env: PYTHON_VERSION=3.3 NUMPY_VERSION=1.9.2 SCIPY_VERSION=0.15.1 MATPLOTLIB_VERSION=1.4.3 LMFIT_VERSION=0.9.3
    - os: linux
      env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.10.2 SCIPY_VERSION=0.16.1 MATPLOTLIB_VERSION=1.5.1 LMFIT_VERSION=0.9.3
    - os: linux
      env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.10.2 SCIPY_VERSION=0.16.1 MATPLOTLIB_VERSION=1.5.1 LMFIT_VERSION=0.9.3
    - os: osx
      env: PYTHON_VERSION=2.6 NUMPY_VERSION=1.9.2 SCIPY_VERSION=0.14 MATPLOTLIB_VERSION=1.4.3 LMFIT_VERSION=0.9.1
    - os: osx
      env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.10.2 SCIPY_VERSION=0.16.1 MATPLOTLIB_VERSION=1.5.1 LMFIT_VERSION=0.9.3
    - os: osx
      env: PYTHON_VERSION=3.3 NUMPY_VERSION=1.9.2 SCIPY_VERSION=0.15.1 MATPLOTLIB_VERSION=1.4.3 LMFIT_VERSION=0.9.3
    - os: osx
      env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.10.2 SCIPY_VERSION=0.16.1 MATPLOTLIB_VERSION=1.5.1 LMFIT_VERSION=0.9.3
    - os: osx
      env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.10.2 SCIPY_VERSION=0.16.1 MATPLOTLIB_VERSION=1.5.1 LMFIT_VERSION=0.9.3
cache: apt
addons:
  apt:
    packages:
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
install:
  - conda create --yes -q -n test_environment python=$PYTHON_VERSION nomkl pip setuptools numpy=$NUMPY_VERSION scipy=$SCIPY_VERSION matplotlib=$MATPLOTLIB_VERSION mock h5py pep8
  - source activate test_environment
  - if ! ( [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$PYTHON_VERSION" == "2.6" ] ); then pip install codeclimate-test-reporter ordereddict lmfit==$LMFIT_VERSION pytest-cov pytest-pep8; else easy_install ordereddict codeclimate-test-reporter pytest-cov pytest-pep8 lmfit==$LMFIT_VERSION; fi
  - pip install -e . -q --no-deps
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
    fi
script:
  - pytest --cov=neutronpy --tb=short
after_success:
  - coverage run neutronpy
  - coveralls
deploy:
  - provider: pypi
    user: davidfobes
    password:
      secure: DdjBSsRSENkuRtzzbCJMEwhO2RXkER1RrBqKLdH+2TeC0w+CiYqUf3x/h2yWs5IdNjf6Q5UWx68vau7ylJpESiQbiP++MGeKguEHQOiLcFhUDz/wxZCk20GsWNsox00ISALVF02nH1eq3mcVkKqCzt8WzNZ/Ioey+aHJI1KwrtU=
    on:
      tags: true
      branch: master
      condition: $TRAVIS_OS_NAME = "osx"
    distributions: bdist_wheel
  - provider: pypi
    user: davidfobes
    password:
      secure: DdjBSsRSENkuRtzzbCJMEwhO2RXkER1RrBqKLdH+2TeC0w+CiYqUf3x/h2yWs5IdNjf6Q5UWx68vau7ylJpESiQbiP++MGeKguEHQOiLcFhUDz/wxZCk20GsWNsox00ISALVF02nH1eq3mcVkKqCzt8WzNZ/Ioey+aHJI1KwrtU=
    on:
      tags: true
      branch: master
      condition: ($TRAVIS_OS_NAME = "osx") && ($PYTHON_VERSION = "3.5")
    distributions: sdist
notifications:
  slack:
    secure: qsq1keqgpaE8P2uziBCorm27rLwUet0FHsf4CKo92faxL9q4FfBYkGFBgcTvKuDsImNz7P3cvLRNDkCxoklKNBtSJmS8DPDLINJikDDm0Tll7oX3pXox+I/x487AkiwyI/xjRKoH7pO+v/iVLVfznL228ABeactMj8OTsccwO0Q=
  email: false
