# Check on http://lint.travis-ci.org/ after modifying it!  Originally
# modified from https://gist.github.com/dan-blanchard/7045057
language: python
env:
  - PYTHON_VERSION=2.6 NUMPY_VERSION=1.8 SCIPY_VERSION=0.14 USE_CYTHON=TRUE
  - PYTHON_VERSION=2.7 NUMPY_VERSION=1.8 SCIPY_VERSION=0.14 USE_CYTHON=TRUE
  - PYTHON_VERSION=3.3 NUMPY_VERSION=1.8 SCIPY_VERSION=0.14 USE_CYTHON=TRUE
  - PYTHON_VERSION=3.4 NUMPY_VERSION=1.8 SCIPY_VERSION=0.14 USE_CYTHON=TRUE 
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$PYTHON_VERSION pip numpy=$NUMPY_VERSION scipy=$SCIPY_VERSION nose pep8 Sphinx
  - if [ ${USE_CYTHON} ]; then conda install --yes -n env_name cython; fi
  - source activate env_name
  - pip install -e . -q --no-deps
script:
  - nosetests
after_success:
  - coveralls