sudo: false
language: python

env:
  global:
    - secure: "CNtkJEHcZrfJ05ccGQdWu62u7YViADRiPskfCBcOaKvR90CmHvscsQLcipShVnM6NAkSw2A6w+BKHUq6qkXF/NjbnFPypUHfMDzSBtkdMstybHfhc32ReZ3dBjWNNzNHD+alCEm9AyoU7Shq0nM2/X0TNBFZHSLa2b1GHprdndA="

matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
  allow_failures:
    - python: "3.7-dev"
    - python: "3.8-dev"

install:
  - pip install pytest pytest-cov mock codecov
  - pip install -e . -q

before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 10;

script:
  - pytest --cov=neutronpy --tb=short

after_success:
  - codecov
  - chmod +x ./.deploy_anaconda.sh
  - git reset --hard HEAD

deploy:
  - provider: pypi
    user: davidfobes
    password:
      secure: DdjBSsRSENkuRtzzbCJMEwhO2RXkER1RrBqKLdH+2TeC0w+CiYqUf3x/h2yWs5IdNjf6Q5UWx68vau7ylJpESiQbiP++MGeKguEHQOiLcFhUDz/wxZCk20GsWNsox00ISALVF02nH1eq3mcVkKqCzt8WzNZ/Ioey+aHJI1KwrtU=
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    on:
      tags: true
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = '3.6'

  - provider: script
    script: ./.deploy_anaconda.sh
    skip_cleanup: true
    on:
      tags: true
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = '3.6'

notifications:
  slack:
    secure: qsq1keqgpaE8P2uziBCorm27rLwUet0FHsf4CKo92faxL9q4FfBYkGFBgcTvKuDsImNz7P3cvLRNDkCxoklKNBtSJmS8DPDLINJikDDm0Tll7oX3pXox+I/x487AkiwyI/xjRKoH7pO+v/iVLVfznL228ABeactMj8OTsccwO0Q=
  email: false
