environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

matrix:
  fast_finish: true
  allow_failures:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -U -q setuptools"
  - "%PYTHON%\\python.exe -m pip install -q wheel pytest mock numpy scipy matplotlib h5py"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 4puZDYgXn4YqvOjHCgtGlddjkbJEYtgD8wIdf4ifEvuiHRZD7cjnRoAd6zmGfvjwV6nPe9zbUsOjGF46WlRCFN2QQzftsdO9VsbaErBvtSA=
