{% set data = load_setup_py_data() %}
package:
  name: neutronpy
  version: {{ data.get('version') }}

source:
  path: ../
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch: python
  # preserve_egg_dir: True
  entry_points:
    - neutronpy = neutronpy.gui:launch
  number: {{ data.get('version') }}

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - lmfit
    - h5py

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - lmfit
    - h5py

test:
  # Python imports
  imports:
    - neutronpy
    - neutronpy.crystal
    - neutronpy.data
    - neutronpy.fileio
    - neutronpy.fileio.loaders
    - neutronpy.instrument
    - neutronpy.lsfit
    - neutronpy.scattering

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    # - neutronpy --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/neutronpy/neutronpy
  license: MIT License
  summary: 'NeutronPy: Neutron scattering tools for scientific data analysis in python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
